import { AppInputs } from "@ghostwriter/server";
import { Dialog, Menu, Transition } from "@headlessui/react";
import { Fragment, useState, type FC } from "react";
import { trpc } from "../../../lib/trpc";

const Create: FC = () => {
  const [isOpen, setIsOpen] = useState(false);
  const [option, setOption] = useState<AppInputs["newContent"]>({
    kind: "ai",
    topic: "",
  });
  const utils = trpc.useUtils();

  const { mutate, isLoading } = trpc.newContent.useMutation({
    onSuccess: async () => {
      await utils.contents.invalidate();
      setIsOpen(false);
      setOption({
        kind: "ai",
        topic: "",
      });
    },
  });

  return (
    <>
      <button
        className="inline-flex justify-center rounded-md border border-transparent px-3 py-1.5 text-sm font-medium bg-vista-100  text-vista-900 hover:bg-vista-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
        onClick={() => setIsOpen(true)}
      >
        Create
      </button>
      <Transition appear show={isOpen} as={Fragment}>
        <Dialog
          as="div"
          className="relative z-10"
          onClose={() => setIsOpen(false)}
        >
          <Transition.Child
            as={Fragment}
            enter="ease-out duration-300"
            enterFrom="opacity-0"
            enterTo="opacity-100"
            leave="ease-in duration-200"
            leaveFrom="opacity-100"
            leaveTo="opacity-0"
          >
            <div className="fixed inset-0 bg-black bg-opacity-25" />
          </Transition.Child>

          <div className="fixed inset-0 overflow-y-auto">
            <div className="flex min-h-full items-center justify-center p-4 text-center">
              <Transition.Child
                as={Fragment}
                enter="ease-out duration-300"
                enterFrom="opacity-0 scale-95"
                enterTo="opacity-100 scale-100"
                leave="ease-in duration-200"
                leaveFrom="opacity-100 scale-100"
                leaveTo="opacity-0 scale-95"
              >
                <Dialog.Panel className="w-[90%] md:max-w-xl transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all">
                  <div className="w-full flex items-center gap-2">
                    <Menu as="div" className="relative inline-block text-left">
                      <div>
                        <Menu.Button className="inline-flex items-center gap-1.5 rounded py-1 px-2 border border-black/15">
                          <span
                            className="w-2 h-2 rounded-full data-[kind=ai]:bg-vista-400 data-[kind=custom]:bg-purple-400"
                            data-kind={option.kind}
                          />
                          <span className="font-mono text-xs font-medium">
                            {option.kind}
                          </span>
                        </Menu.Button>
                      </div>
                      <Transition
                        as={Fragment}
                        enter="transition ease-out duration-100"
                        enterFrom="transform opacity-0 scale-95"
                        enterTo="transform opacity-100 scale-100"
                        leave="transition ease-in duration-75"
                        leaveFrom="transform opacity-100 scale-100"
                        leaveTo="transform opacity-0 scale-95"
                      >
                        <Menu.Items className="absolute left-0 mt-2 w-56 origin-top-left divide-y divide-gray-100 rounded-md bg-white shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none">
                          <div className="px-1 py-1 ">
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className="group flex w-full items-center rounded-md px-2 py-2 gap-1.5 data-active:bg-vista-50"
                                  data-active={active}
                                >
                                  <span className="w-2 h-2 rounded-full bg-vista-400" />
                                  <span className="font-mono text-xs font-medium">
                                    ai
                                  </span>
                                  <span className="ml-1 text-xs text-black/40">
                                    Generated by AI
                                  </span>
                                </button>
                              )}
                            </Menu.Item>
                            <Menu.Item>
                              {({ active }) => (
                                <button
                                  className="group flex w-full items-center rounded-md px-2 py-2 gap-1.5 data-active:bg-purple-50 disabled:opacity-50 disabled:cursor-not-allowed"
                                  data-active={active}
                                  disabled
                                >
                                  <span className="w-2 h-2 rounded-full bg-purple-400" />
                                  <span className="font-mono text-xs font-medium">
                                    custom
                                  </span>
                                  <span className="ml-1 text-xs text-black/40">
                                    Provide a script
                                  </span>
                                </button>
                              )}
                            </Menu.Item>
                          </div>
                        </Menu.Items>
                      </Transition>
                    </Menu>
                    <Dialog.Title
                      as="span"
                      className="text-sm inline-flex items-center gap-2"
                    >
                      <span>⟩</span>
                      <span className="font-medium">New video</span>
                    </Dialog.Title>
                  </div>
                  {option.kind === "ai" && (
                    <textarea
                      placeholder="Write a topic or story..."
                      className="mt-3 w-full outline-none font-normal placeholder-black/50 min-h-[9rem]"
                      value={option.topic}
                      onChange={(e) => {
                        setOption({
                          ...option,
                          topic: e.target.value,
                        });
                      }}
                    ></textarea>
                  )}

                  <div className="flex w-full items-center justify-end mt-4">
                    <button
                      type="button"
                      className="inline-flex justify-center rounded-md border border-transparent px-3 py-1.5 text-sm font-medium bg-vista-100  text-vista-900 hover:bg-vista-200 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 focus-visible:ring-offset-2"
                      disabled={isLoading}
                      onClick={() => mutate(option)}
                    >
                      {isLoading ? "Cooking..." : "Let it cook!"}
                    </button>
                  </div>
                </Dialog.Panel>
              </Transition.Child>
            </div>
          </div>
        </Dialog>
      </Transition>
    </>
  );
};

export default Create;
