import { consola } from "consola";
import { mkdir } from "node:fs/promises";
import { input } from "./env.js";
import { meta, script } from "./script/writer.js";
import { direct } from "./video/record.js";
import { combineVoices, voice } from "./voice/speech.js";

async function main() {
  const option = await input({
    fn: () =>
      consola.prompt("Auto-generate script or prefilled?", {
        type: "select",
        options: [
          {
            label: "AI Generated",
            hint: "Automatically generated by AI with a custom topic",
            value: "ai",
          },
          {
            label: "Custom script",
            hint: "Provide a script",
            value: "custom",
          },
        ],
      }) as any as Promise<"ai" | "custom">,
    or: (e) => e.OPTION,
  });

  const start = Date.now();
  consola.start(`Generating script... ${option}`);

  await mkdir("out", { recursive: true });

  const res = await script(option as any as "ai" | "custom");

  consola.success(`Generated script! (Took ${Date.now() - start}ms)`);

  for (const script of res) {
    const startVoice = Date.now();
    consola.start("Generating voices...");

    const times = [];

    for (const i in script) {
      const { name, content } = script[i];
      const res = await voice(name, content, `out/temp-${i}.mp3`);
      if (res.status != "ok") {
        consola.error(`Failed to generate voice for ${name}`);
        return;
      }
      times.push(res.time);
    }
    consola.success(`Generated voices! (Took ${Date.now() - startVoice}ms)`);

    await meta(option as any, script, times);

    const startCombining = Date.now();
    consola.start("Combining voices...");

    await combineVoices(script);

    consola.success(`Combined voices! (Took ${Date.now() - startCombining}ms)`);

    const startVideo = Date.now();
    consola.start("Generating video...");

    await direct();

    consola.success(`Generated video! (Took ${Date.now() - startVideo}ms)`);
  }
  consola.info(`All process in total took ${Date.now() - start}ms`);
}

main();
